name: period_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.2
  intl: ^0.18.1
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.0.0
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  fl_chart: ^0.66.0
  pdf: ^3.10.8
  printing: ^5.11.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  timezone: ^0.9.2
  android_alarm_manager_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: 3.1.0+1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true